name: "Hello Actions"
description: "Greetings!"
author: "Harveyhu@microsoft.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Friends"

runs:
  using: docker
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "blue"  